### ISSUE TITLE
Jupinx has problem with Inserting code 

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#11]
For switching to code mode we are using double `'` ( ' ' ) which Jupinx can't support them like : 

``R`` needs to be a matrix where ``R[s, a]`` is the reward at state ``s`` under action ``a``

![screenshot from 2018-08-29 17-03-59](https://user-images.githubusercontent.com/20714542/44771952-e2f2f580-abaf-11e8-88cf-863296be08d6.png)

**Comment by fkazemian** [comment]
![1](https://user-images.githubusercontent.com/20714542/45005812-d7cd1900-b038-11e8-8396-f5a6c7a4d223.png)
(arellano) - the code is
`3.  Update the value function `v(B, y)`, the default rule,  the implied ex ante default probability,  and the price function`

**Comment by mmcky** [comment]
this should be fixed by https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/86

**Comment by fkazemian** [comment]
Hi @mmcky , It is not fixed, for example aiyagari:

![screenshot from 2018-09-06 14-29-28](https://user-images.githubusercontent.com/20714542/45135203-7f854b00-b1e1-11e8-9b70-85b022c1fb9a.png)
code:

* ``R`` needs to be a matrix where ``R[s, a]`` is the reward at state ``s`` under action ``a``

* ``Q`` needs to be a three dimensional array where ``Q[s, a, s']`` is the probability of transitioning to state ``s'`` when the current state is ``s`` and the current action is ``a`` 

(For a detailed discussion of ``DiscreteDP`` see :doc:`this lecture <discrete_dp>`)

**Comment by mmcky** [comment]
@fkazemian would you mind checking this issue again. I think it should be resolved now with the latest compilation. Thanks

**Comment by fkazemian** [comment]
Hi @mmcky , Thanks it fixed, I just change the label from bug to ready. thanks

**Comment by mmcky** [comment]
thanks @fkazemian

**Comment by fkazemian** [comment]
Hi @mmcky sorry, but I just saw some minor problem with this issue, for example in (lake_model)

![screenshot from 2018-09-07 15-04-36](https://user-images.githubusercontent.com/20714542/45199649-36e89300-b2b0-11e8-8ba4-04374b5f56d0.png)
![screenshot from 2018-09-07 15-03-42](https://user-images.githubusercontent.com/20714542/45199652-3819c000-b2b0-11e8-9295-0c9141708862.png)
code
`To do this we're going to use a class that we'll call `LakeModel``
`To achieve this outcome, we're going to use descriptors and decorators such as `@property``

**Comment by fkazemian** [comment]
![screenshot from 2018-09-10 16-19-52](https://user-images.githubusercontent.com/20714542/45280661-9e088080-b518-11e8-87d9-ae44705ccff8.png)
```
We will define a function `tree_price` to solve for $v$ given parameters stored in
the class `AssetPriceModel`
```
![screenshot from 2018-09-10 16-20-36](https://user-images.githubusercontent.com/20714542/45280690-bb3d4f00-b518-11e8-9f12-67968910db84.png)
`The above is implemented in the function `consol_price``

![screenshot from 2018-09-10 16-23-32](https://user-images.githubusercontent.com/20714542/45280730-df992b80-b518-11e8-8638-a68ba5a7fb35.png)

`We can find the solution with the following function `call_option``

**Comment by fkazemian** [comment]
Hi @mmcky ,
This issue somewhere is fixed but somewhere not,
for example in (markov_perf):
![screenshot from 2018-09-11 09-59-57](https://user-images.githubusercontent.com/20714542/45330705-06ec0900-b5aa-11e8-8929-fc380a6744fe.png)
![screenshot from 2018-09-11 09-58-37](https://user-images.githubusercontent.com/20714542/45330706-081d3600-b5aa-11e8-80bd-3326630291e7.png)
