### ISSUE TITLE
(None) appearing in some situations within the text when using inter-file links

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#27]
In (finite_markov), the code is fine and there is no problem with tags, but I don't know why there is an extra word `(None)` in Generated version! 
![screenshot from 2018-09-07 11-15-55](https://user-images.githubusercontent.com/20714542/45193925-00048400-b294-11e8-99d1-df837f1fb26c.png)

The code is:
```
There are :math:`n` such equations, one for each :math:`y \in S`

If we think of :math:`\psi_{t+1}` and :math:`\psi_t` as *row vectors* (as is traditional in this literature), these :math:`n` equations are summarized by the matrix expression

```

----------------------------------------------------------------------------------------------------------------

(PR #40) Fixed

**Comment by fkazemian** [comment]
samuelson:
link is dismissed 
![screenshot from 2018-09-12 13-16-31](https://user-images.githubusercontent.com/20714542/45400511-c961ab80-b68f-11e8-9c6c-84d73639a171.png)
```

We also show how to map the Samuelson model into a simple instance of
   the `LinearStateSpace` class described `here <https://lectures.quantecon.org/py/linear\_models.html>`__
```

**Comment by mmcky** [comment]
**finite_markov**

```rst
Rewriting this statement in terms of  marginal and conditional probabilities gives

.. _mc_fdd:

.. math::

    \psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)


There are :math:`n` such equations, one for each :math:`y \in S`

If we think of :math:`\psi_{t+1}` and :math:`\psi_t` as *row vectors* (as is traditional in this literature), these :math:`n` equations are summarized by the matrix expression

.. _mc_fddv:

.. math::
    :label: fin_mc_fr

    \psi_{t+1} = \psi_t P
```

The issue here is the preceding label to the math block is causing the extension to think that the math is labelled but it has no label number. These are links used from another lecture to link to this point in this lecture.

**Comment by mmcky** [comment]
@fkazemian can we label the `math` with `mc_fdd` and use that link in other lectures? Would you mind checking?

**Comment by mmcky** [comment]
re ``harrison_kreps``

I will change the implementation of ``block-quote`` in the extension to match markdown properly. Currently we are using 4 spaces but it should use `>`

**Comment by fkazemian** [comment]
Hi @mmcky 
`mc_fdd` is used only in these lectures:
```
./source/py/stationary_densities.rst:answer :ref:`we gave <mc_fdd>` was that
./source/py/stationary_densities.rst:    parallel with the finite case --- see :ref:`here <mc_fddv>`
./source/py/finite_markov.rst:.. _mc_fdd:
./source/py/finite_markov.rst:.. _mc_fddv:
./source/jl/stationary_densities.rst:answer :ref:`we gave <mc_fdd>` was that
./source/jl/stationary_densities.rst:    parallel with the finite case --- see :ref:`here <mc_fddv>`
./source/jl/finite_markov.rst:.. _mc_fdd:
./source/jl/finite_markov.rst:.. _mc_fddv:

```

**Comment by fkazemian** [comment]
> In (finite_markov), the code is fine and there is no problem with tags, but I don't know why there is an extra word `(None)` in Generated version!
> ![screenshot from 2018-09-07 11-15-55](https://user-images.githubusercontent.com/20714542/45193925-00048400-b294-11e8-99d1-df837f1fb26c.png)
> 
> The code is:
> 
> ```
> There are :math:`n` such equations, one for each :math:`y \in S`
> 
> If we think of :math:`\psi_{t+1}` and :math:`\psi_t` as *row vectors* (as is traditional in this literature), these :math:`n` equations are summarized by the matrix expression
> ```
This is not because of 
`If we think of :math:`\psi_{t+1}` and :math:`\psi_t` as *row vectors* (as is traditional in this literature), these :math:`n` equations are summarized by the matrix expression
 `

this is because of the formula before that. It was something like
```
.. _mc_fdd:

.. math::

\psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)
```

I add some space before `.. math::` like

```
.. _mc_fdd:

    .. math::

    \psi_{t+1}(y) = \sum_{x \in S} P(x,y) \psi_t(x)

```
and that (None) disappeared.

**Comment by mmcky** [comment]
@fkazemian I think the math should be indented again to be contained in the `math` directive?

**Comment by mmcky** [comment]
@fkazemian are these now fixed?

**Comment by fkazemian** [comment]
Hi @mmcky 
finite_markov is not fixed : 
![screenshot from 2018-10-03 16-02-09](https://user-images.githubusercontent.com/20714542/46392786-eb49cd80-c725-11e8-82ee-9236bc2d4e6c.png)

**Comment by mmcky** [comment]
@fkazemian I am a little confused. Isn't `finite_markov` fixed by https://github.com/QuantEcon/lecture-source-py/pull/40?

**Comment by mmcky** [comment]
@fkazemian it looks like the spacing in `Samuelson` rst just needs to be fixed. can you submit a PR?

```rat
We also show how to map the Samuelson model into a simple instance of
   the `LinearStateSpace` class described `here <https://lectures.quantecon.org/py/linear\_models.html>`__

We can use a `LinearStateSpace` instance to do various things that we did above with
   our homemade function and class
```

**Comment by fkazemian** [comment]
Hi @mmcky I checked them by http://compare-lectures.quantecon.org/, you are not merging #40 yet, so It's not fixed yet

**Comment by fkazemian** [comment]
@mmcky sure I'll do it now

**Comment by fkazemian** [comment]
Hi @mmcky 
I add an space but it is not solved:
```
We also show how to map the Samuelson model into a simple instance of
   the `LinearStateSpace` class described `here <https://lectures.quantecon.org/py/linear\_models.html>`__

```
![screenshot from 2018-10-03 17-00-51](https://user-images.githubusercontent.com/20714542/46394956-16d0b600-c72e-11e8-81a2-79201f7d5796.png)

**Comment by mmcky** [comment]
@Fazeleh Kazemian <fazeleh.kazemian@gmail.com> I suspect the space should
be removed as the indentation shouldn't be there. Is that what you mean?

**Comment by fkazemian** [comment]
@mmcky actually with space and without space it is not working. without space is something like:
![screenshot from 2018-10-03 17-11-01](https://user-images.githubusercontent.com/20714542/46395338-5cda4980-c72f-11e8-997f-226251b5b44f.png)
`   the `LinearStateSpace` class described `here<https://lectures.quantecon.org/py/linear\_models.html>`__`

**Comment by fkazemian** [comment]
I'll check it and try to fix it.

**Comment by fkazemian** [comment]
I found it, @mmcky  link has conflict with the space at the beginning of the line
![screenshot from 2018-10-03 17-40-37](https://user-images.githubusercontent.com/20714542/46397514-c5c4c000-c735-11e8-9064-d7e074f5392b.png)

**Comment by mmcky** [comment]
thanks @fkazemian can you submit a PR when you're ready.

**Comment by fkazemian** [comment]
Hi @mmcky I think this issue is fixed, we only need to merge their PRs

**Comment by mmcky** [comment]
thanks @fkazemian.
